apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: go-demo-v2
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: go-demo-v2
    spec:
      containers:
      - name: go-demo-v2
        image: mjsdemoreg.azurecr.io/go-demo-v2:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: go-demo-v2
spec:
  type: LoadBalancer
  ports:
  - port: 8000
  selector:
    app: go-demo-v2